// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20261003110903_001")]
    partial class _001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("BrandName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("OriginRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Hồng Lam",
                            Description = "Thương hiệu tinh hoa quà Việt, chuyên ô mai và mứt truyền thống",
                            OriginRegion = "Hà Nội"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Tân Huê Viên",
                            Description = "Thương hiệu bánh pía và lạp xưởng nổi tiếng Miền Tây",
                            OriginRegion = "Sóc Trăng"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Yến Hoàng",
                            Description = "Chuyên kẹo dừa và các sản phẩm chế biến từ dừa nguyên chất",
                            OriginRegion = "Bến Tre"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "L'angfarm",
                            Description = "Đặc sản Đà Lạt, trái cây sấy khô và trà thảo mộc",
                            OriginRegion = "Đà Lạt"
                        },
                        new
                        {
                            BrandId = 5,
                            BrandName = "Đặc Sản Tây Bắc",
                            Description = "Thịt sấy, gia vị chẩm chéo và nông sản vùng cao",
                            OriginRegion = "Hà Giang - Sơn La"
                        },
                        new
                        {
                            BrandId = 6,
                            BrandName = "Bảo Minh",
                            Description = "Chuyên bánh cốm, bánh đậu xanh và bánh kẹo truyền thống Miền Bắc",
                            OriginRegion = "Hà Nội"
                        },
                        new
                        {
                            BrandId = 7,
                            BrandName = "Hà Xua",
                            Description = "Đặc sản tré rơm, nem chả và thủy hải sản khô Quy Nhơn",
                            OriginRegion = "Bình Định"
                        },
                        new
                        {
                            BrandId = 8,
                            BrandName = "Phú Hương",
                            Description = "Nước mắm truyền thống và mực khô sấy sa tế Phú Quốc",
                            OriginRegion = "Phú Quốc"
                        },
                        new
                        {
                            BrandId = 9,
                            BrandName = "Xưởng Ăn Vặt Sài Gòn",
                            Description = "Cơm cháy chà bông, bánh tráng trộn và các món ăn vặt hiện đại",
                            OriginRegion = "TP. Hồ Chí Minh"
                        },
                        new
                        {
                            BrandId = 10,
                            BrandName = "Trà Tân Cương",
                            Description = "Trà đinh, trà mộc thượng hạng chuẩn vùng Thái Nguyên",
                            OriginRegion = "Thái Nguyên"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Đặc sản Miền Bắc",
                            Description = "Bánh cốm, thịt trâu gắp bếp, ô mai truyền thống"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Đặc sản Miền Trung",
                            Description = "Mực rim sa tế, tré Bình Định, bánh ép Huế"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Đặc sản Miền Tây & Nam Bộ",
                            Description = "Bánh pía Sóc Trăng, kẹo dừa Bến Tre, lạp xưởng"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Trái cây sấy khô & Dẻo",
                            Description = "Mít sấy, xoài sấy dẻo, chuối sấy giòn Đà Lạt"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Đồ ăn vặt mặn",
                            Description = "Cơm cháy chà bông, khô gà lá chanh, bánh tráng"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Trà & Thảo mộc vùng miền",
                            Description = "Trà Thái Nguyên, trà sâm dây Ngọc Linh, trà mướp đắng"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Bánh kẹo truyền thống",
                            Description = "Bánh cốm, bánh đậu xanh, kẹo cu đơ, kẹo chuối"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Thủy hải sản khô & Rim",
                            Description = "Cá chỉ vàng rim, mực xé hấp nước dừa, tôm khô"
                        },
                        new
                        {
                            CategoryId = 9,
                            CategoryName = "Gia vị & Nước chấm đặc sản",
                            Description = "Nước mắm Phú Quốc, muối tôm Tây Ninh, chẩm chéo"
                        },
                        new
                        {
                            CategoryId = 10,
                            CategoryName = "Nước giải khát & Nước trái cây",
                            Description = "Nước dừa tươi đóng lon, nước mủ trôm, nước chanh dây"
                        },
                        new
                        {
                            CategoryId = 11,
                            CategoryName = "Nông sản & Hạt dinh dưỡng",
                            Description = "Hạt điều Bình Phước, hạt macca Tây Nguyên, sen sấy"
                        },
                        new
                        {
                            CategoryId = 12,
                            CategoryName = "Rượu & Đồ uống lên men",
                            Description = "Rượu mận Tả Van, rượu mơ Yên Tử, rượu thốt nốt"
                        },
                        new
                        {
                            CategoryId = 13,
                            CategoryName = "Đặc sản Tây Nguyên",
                            Description = "Cà phê Cầu Đất, tiêu Chư Sê, măng khô Kon Tum"
                        },
                        new
                        {
                            CategoryId = 14,
                            CategoryName = "Mứt & Trái cây ngâm",
                            Description = "Mứt dâu tây Đà Lạt, dầm sấu, mứt quất hồng giòn"
                        },
                        new
                        {
                            CategoryId = 15,
                            CategoryName = "Combo & Hộp quà đặc sản",
                            Description = "Bộ quà tặng đặc sản 3 miền, hộp quà Tết vùng miền"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Address = "123 Lê Lợi, Q.1, TP.HCM",
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 210
                        },
                        new
                        {
                            CustomerId = 2,
                            Address = "456 Nguyễn Trãi, Q.5, TP.HCM",
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 85
                        },
                        new
                        {
                            CustomerId = 3,
                            Address = "78 Điện Biên Phủ, Q.3, TP.HCM",
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 25
                        },
                        new
                        {
                            CustomerId = 4,
                            Address = "12 Cách Mạng Tháng 8, Q.10, TP.HCM",
                            CustomerName = "Phạm Thị D",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0934567890",
                            RewardPoints = 540
                        },
                        new
                        {
                            CustomerId = 5,
                            Address = "89 Hoàng Văn Thụ, Q.Phú Nhuận, TP.HCM",
                            CustomerName = "Hoàng Minh E",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0971122444",
                            RewardPoints = 110
                        },
                        new
                        {
                            CustomerId = 6,
                            Address = "204 Nguyễn Thị Minh Khai, Q.3, TP.HCM",
                            CustomerName = "Đỗ Thu F",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0909988776",
                            RewardPoints = 15
                        },
                        new
                        {
                            CustomerId = 7,
                            Address = "55 Phan Đăng Lưu, Q.Bình Thạnh, TP.HCM",
                            CustomerName = "Vũ Quốc G",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0945112233",
                            RewardPoints = 320
                        },
                        new
                        {
                            CustomerId = 8,
                            Address = "15 Nguyễn Hữu Cảnh, Q.Bình Thạnh, TP.HCM",
                            CustomerName = "Đặng Mai H",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0966778899",
                            RewardPoints = 0
                        },
                        new
                        {
                            CustomerId = 9,
                            Address = "88 Lý Thường Kiệt, Q.10, TP.HCM",
                            CustomerName = "Bùi Anh Khoa",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0931223344",
                            RewardPoints = 95
                        },
                        new
                        {
                            CustomerId = 10,
                            Address = "302 Võ Văn Tần, Q.3, TP.HCM",
                            CustomerName = "Ngô Bích Ngọc",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0978990011",
                            RewardPoints = 280
                        },
                        new
                        {
                            CustomerId = 11,
                            Address = "12 Trần Hưng Đạo, Q.1, TP.HCM",
                            CustomerName = "Trịnh Quốc Bảo",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0903445566",
                            RewardPoints = 40
                        },
                        new
                        {
                            CustomerId = 12,
                            Address = "74 Ba Tháng Hai, Q.10, TP.HCM",
                            CustomerName = "Lý Mỹ Duyên",
                            MembershipRank = "Kim Cương",
                            PhoneNumber = "0915667788",
                            RewardPoints = 610
                        },
                        new
                        {
                            CustomerId = 13,
                            Address = "450 Xô Viết Nghệ Tĩnh, Q.Bình Thạnh, TP.HCM",
                            CustomerName = "Đoàn Tấn Phát",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0982114455",
                            RewardPoints = 130
                        },
                        new
                        {
                            CustomerId = 14,
                            Address = "19 An Dương Vương, Q.5, TP.HCM",
                            CustomerName = "Dương Khánh Linh",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0947889900",
                            RewardPoints = 10
                        },
                        new
                        {
                            CustomerId = 15,
                            Address = "500 Cộng Hòa, Q.Tân Bình, TP.HCM",
                            CustomerName = "Phan Hoài Nam",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0963221100",
                            RewardPoints = 190
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.InventoryLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("BatchNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("int");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("LogId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SupplierId");

                    b.ToTable("InventoryLogs");

                    b.HasData(
                        new
                        {
                            LogId = 1,
                            BatchNumber = "LOT-TB-20260301",
                            ExpirationDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "Nhập kho lô thịt trâu gắp bếp Tây Bắc",
                            ProductId = 1,
                            QuantityChange = 20,
                            TransactionDate = new DateTime(2026, 3, 1, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "IMPORT"
                        },
                        new
                        {
                            LogId = 2,
                            BatchNumber = "LOT-THV-20260305",
                            ExpirationDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Note = "Nhập kho bánh pía Tân Huê Viên",
                            ProductId = 5,
                            QuantityChange = 60,
                            TransactionDate = new DateTime(2026, 3, 5, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            TransactionType = "IMPORT"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            CustomerId = 1,
                            OrderDate = new DateTime(2026, 3, 20, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Banking",
                            PaymentStatus = "Paid",
                            TotalAmount = 265000m
                        },
                        new
                        {
                            OrderId = 2,
                            CustomerId = 2,
                            OrderDate = new DateTime(2026, 3, 22, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            PaymentStatus = "Paid",
                            TotalAmount = 130000m
                        },
                        new
                        {
                            OrderId = 3,
                            CustomerId = 4,
                            OrderDate = new DateTime(2026, 3, 25, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "QR Code",
                            PaymentStatus = "Paid",
                            TotalAmount = 350000m
                        },
                        new
                        {
                            OrderId = 4,
                            CustomerId = 3,
                            OrderDate = new DateTime(2026, 3, 27, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            PaymentMethod = "Cash",
                            PaymentStatus = "Paid",
                            TotalAmount = 97000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");

                    b.HasData(
                        new
                        {
                            OrderDetailId = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 180000m
                        },
                        new
                        {
                            OrderDetailId = 2,
                            OrderId = 1,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 85000m
                        },
                        new
                        {
                            OrderDetailId = 3,
                            OrderId = 2,
                            ProductId = 2,
                            Quantity = 2,
                            UnitPrice = 65000m
                        },
                        new
                        {
                            OrderDetailId = 4,
                            OrderId = 3,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 110000m
                        },
                        new
                        {
                            OrderDetailId = 5,
                            OrderId = 4,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 45000m
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MinStockQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938502000001",
                            BrandId = 5,
                            CategoryId = 1,
                            CostPrice = 135000m,
                            IsActive = true,
                            MinStockQuantity = 5,
                            Price = 180000m,
                            ProductName = "Thịt trâu gắp bếp Tây Bắc 200g",
                            StockQuantity = 18,
                            Unit = "Gói"
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8938502000002",
                            BrandId = 1,
                            CategoryId = 1,
                            CostPrice = 45000m,
                            IsActive = true,
                            MinStockQuantity = 10,
                            Price = 65000m,
                            ProductName = "Ô mai sấu xào Hồng Lam 300g",
                            StockQuantity = 45,
                            Unit = "Hộp"
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8938502000003",
                            BrandId = 7,
                            CategoryId = 2,
                            CostPrice = 82000m,
                            IsActive = true,
                            MinStockQuantity = 5,
                            Price = 110000m,
                            ProductName = "Tré rơm Bình Định (Hộp 10 xâu)",
                            StockQuantity = 20,
                            Unit = "Hộp"
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8938502000004",
                            BrandId = 7,
                            CategoryId = 8,
                            CostPrice = 70000m,
                            IsActive = true,
                            MinStockQuantity = 10,
                            Price = 95000m,
                            ProductName = "Mực rim sa tế Quy Nhơn 250g",
                            StockQuantity = 35,
                            Unit = "Hũ"
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8938502000005",
                            BrandId = 2,
                            CategoryId = 3,
                            CostPrice = 60000m,
                            IsActive = true,
                            MinStockQuantity = 10,
                            Price = 85000m,
                            ProductName = "Bánh pía trứng chảy Sóc Trăng 400g",
                            StockQuantity = 52,
                            Unit = "Túi"
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8938502000006",
                            BrandId = 3,
                            CategoryId = 3,
                            CostPrice = 28000m,
                            IsActive = true,
                            MinStockQuantity = 15,
                            Price = 45000m,
                            ProductName = "Kẹo dừa béo Bến Tre 300g",
                            StockQuantity = 75,
                            Unit = "Gói"
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8938502000007",
                            BrandId = 4,
                            CategoryId = 4,
                            CostPrice = 36000m,
                            IsActive = true,
                            MinStockQuantity = 10,
                            Price = 55000m,
                            ProductName = "Xoài sấy dẻo L'angfarm 200g",
                            StockQuantity = 50,
                            Unit = "Túi"
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8938502000008",
                            BrandId = 4,
                            CategoryId = 4,
                            CostPrice = 27000m,
                            IsActive = true,
                            MinStockQuantity = 12,
                            Price = 42000m,
                            ProductName = "Mít sấy giòn L'angfarm 150g",
                            StockQuantity = 60,
                            Unit = "Túi"
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8938502000009",
                            BrandId = 9,
                            CategoryId = 5,
                            CostPrice = 48000m,
                            IsActive = true,
                            MinStockQuantity = 10,
                            Price = 75000m,
                            ProductName = "Cơm cháy chà bông Sài Gòn 500g",
                            StockQuantity = 40,
                            Unit = "Túi"
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8938502000010",
                            BrandId = 9,
                            CategoryId = 5,
                            CostPrice = 42000m,
                            IsActive = true,
                            MinStockQuantity = 8,
                            Price = 68000m,
                            ProductName = "Khô gà xé lá chanh đậm vị 300g",
                            StockQuantity = 38,
                            Unit = "Hũ"
                        },
                        new
                        {
                            ProductId = 11,
                            Barcode = "8938502000011",
                            BrandId = 10,
                            CategoryId = 6,
                            CostPrice = 85000m,
                            IsActive = true,
                            MinStockQuantity = 5,
                            Price = 120000m,
                            ProductName = "Trà Thái Nguyên thượng hạng 200g",
                            StockQuantity = 32,
                            Unit = "Gói"
                        },
                        new
                        {
                            ProductId = 12,
                            Barcode = "8938502000012",
                            BrandId = 6,
                            CategoryId = 7,
                            CostPrice = 8000m,
                            IsActive = true,
                            MinStockQuantity = 15,
                            Price = 12000m,
                            ProductName = "Bánh cốm Hàng Than Hà Nội 100g",
                            StockQuantity = 80,
                            Unit = "Cái"
                        },
                        new
                        {
                            ProductId = 13,
                            Barcode = "8938502000013",
                            BrandId = 8,
                            CategoryId = 9,
                            CostPrice = 85000m,
                            IsActive = true,
                            MinStockQuantity = 6,
                            Price = 115000m,
                            ProductName = "Nước mắm Phú Quốc Phú Hương 500ml",
                            StockQuantity = 30,
                            Unit = "Chai"
                        },
                        new
                        {
                            ProductId = 14,
                            Barcode = "8938502000014",
                            BrandId = 3,
                            CategoryId = 10,
                            CostPrice = 11000m,
                            IsActive = true,
                            MinStockQuantity = 24,
                            Price = 18000m,
                            ProductName = "Nước dừa tươi đóng lon Bến Tre 330ml",
                            StockQuantity = 120,
                            Unit = "Lon"
                        },
                        new
                        {
                            ProductId = 15,
                            Barcode = "8938502000015",
                            CategoryId = 11,
                            CostPrice = 120000m,
                            IsActive = true,
                            MinStockQuantity = 5,
                            Price = 165000m,
                            ProductName = "Hạt điều rang muối Bình Phước 500g",
                            StockQuantity = 25,
                            Unit = "Hũ"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("DiscountPercent")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PromotionId");

                    b.ToTable("Promotions");

                    b.HasData(
                        new
                        {
                            PromotionId = 1,
                            Code = "DACSAN10K",
                            Description = "Giảm 10.000 VNĐ cho đơn hàng đặc sản từ 200.000 VNĐ",
                            DiscountAmount = 10000m,
                            DiscountPercent = 0.0,
                            EndDate = new DateTime(2026, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PromotionId = 2,
                            Code = "ANVAT10",
                            Description = "Giảm 10% cho tất cả đơn hàng đồ ăn vặt sấy khô",
                            DiscountAmount = 0m,
                            DiscountPercent = 10.0,
                            EndDate = new DateTime(2026, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            StartDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            PromotionId = 3,
                            Code = "TET2026",
                            Description = "Chương trình quà tặng đặc sản mừng lễ",
                            DiscountAmount = 20000m,
                            DiscountPercent = 0.0,
                            EndDate = new DateTime(2026, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = false,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OriginRegion")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Thành phố Sơn La, Tỉnh Sơn La",
                            ContactName = "Nguyễn Văn Hùng",
                            OriginRegion = "Sơn La - Hà Giang",
                            PhoneNumber = "0988111222",
                            SupplierName = "Công ty TNHH Đặc Sản Tây Bắc"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "KCN Quang Minh, Mê Linh, Hà Nội",
                            ContactName = "Trần Thu Hà",
                            OriginRegion = "Hà Nội",
                            PhoneNumber = "0912333444",
                            SupplierName = "Cơ sở Sản xuất Ô mai Hồng Lam"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "Quy Đức, Châu Thành, Sóc Trăng",
                            ContactName = "Thái Tuấn",
                            OriginRegion = "Sóc Trăng",
                            PhoneNumber = "02993888999",
                            SupplierName = "Công ty TNHH Bánh Pía Tân Huê Viên"
                        },
                        new
                        {
                            SupplierId = 4,
                            Address = "Mỏ Cày Bắc, Bến Tre",
                            ContactName = "Lê Thị Lan",
                            OriginRegion = "Bến Tre",
                            PhoneNumber = "0903555666",
                            SupplierName = "Xưởng Kẹo Dừa Bến Tre Yến Hoàng"
                        },
                        new
                        {
                            SupplierId = 5,
                            Address = "Phường 10, TP. Đà Lạt, Lâm Đồng",
                            ContactName = "Phạm Quốc Bảo",
                            OriginRegion = "Đà Lạt",
                            PhoneNumber = "02633888777",
                            SupplierName = "Nông Sản Sấy L'angfarm Đà Lạt"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Quản Lý Cửa Hàng",
                            IsActive = true,
                            PasswordHash = "admin123_hash",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            FullName = "Thu Ngân - Nguyễn Mai",
                            IsActive = true,
                            PasswordHash = "cashier123_hash",
                            Role = "Cashier",
                            Username = "cashier01"
                        },
                        new
                        {
                            UserId = 3,
                            FullName = "Thủ Kho - Trần Tuấn",
                            IsActive = true,
                            PasswordHash = "warehouse123_hash",
                            Role = "Warehouse",
                            Username = "warehouse01"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.InventoryLog", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Product", "Product")
                        .WithMany("InventoryLogs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Supplier", null)
                        .WithMany("InventoryLogs")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.OrderDetail", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSupermarket.API.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId");

                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Navigation("InventoryLogs");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Supplier", b =>
                {
                    b.Navigation("InventoryLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
