// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSupermarket.API.Data;

#nullable disable

namespace MiniSupermarket.API.Migrations
{
    [DbContext(typeof(SupermarketDbContext))]
    [Migration("20260926170648_sa")]
    partial class sa
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Rau củ quả hữu cơ",
                            Description = "Rau xanh, củ quả tươi đạt chuẩn organic"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Ngũ cốc & Hạt dinh dưỡng",
                            Description = "Yến mạch, hạt chia, hạnh nhân, óc chó"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Sữa hạt & Sữa chua hữu cơ",
                            Description = "Sữa hạnh nhân, sữa đậu nành, sữa chua Hy Lạp"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Thực phẩm Eat Clean",
                            Description = "Ức gà, cơm gạo lứt, salad đóng gói ăn kiêng"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Gia vị & Dầu thực vật tự nhiên",
                            Description = "Dầu oliu, mật ong nguyên chất, muối hồng Himalaya"
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MembershipRank")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RewardPoints")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerName = "Nguyễn Văn A",
                            MembershipRank = "Vàng",
                            PhoneNumber = "0901122334",
                            RewardPoints = 150
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerName = "Trần Thị B",
                            MembershipRank = "Bạc",
                            PhoneNumber = "0918877665",
                            RewardPoints = 50
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerName = "Lê Văn C",
                            MembershipRank = "Chuẩn",
                            PhoneNumber = "0983344556",
                            RewardPoints = 10
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Barcode = "8938501234561",
                            CategoryId = 1,
                            Price = 25000m,
                            ProductName = "Rau cải bó xôi hữu cơ 300g",
                            StockQuantity = 50
                        },
                        new
                        {
                            ProductId = 2,
                            Barcode = "8938501234562",
                            CategoryId = 1,
                            Price = 32000m,
                            ProductName = "Cà chua bi hữu cơ 500g",
                            StockQuantity = 40
                        },
                        new
                        {
                            ProductId = 3,
                            Barcode = "8938501234563",
                            CategoryId = 2,
                            Price = 65000m,
                            ProductName = "Yến mạch nguyên hạt Quaker 500g",
                            StockQuantity = 30
                        },
                        new
                        {
                            ProductId = 4,
                            Barcode = "8938501234564",
                            CategoryId = 2,
                            Price = 95000m,
                            ProductName = "Hạt hạnh nhân rang Mỹ 250g",
                            StockQuantity = 25
                        },
                        new
                        {
                            ProductId = 5,
                            Barcode = "8938501234565",
                            CategoryId = 3,
                            Price = 78000m,
                            ProductName = "Sữa hạnh nhân Alsafi 946ml",
                            StockQuantity = 35
                        },
                        new
                        {
                            ProductId = 6,
                            Barcode = "8938501234566",
                            CategoryId = 3,
                            Price = 55000m,
                            ProductName = "Sữa chua Hy Lạp không đường 500g",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 7,
                            Barcode = "8938501234567",
                            CategoryId = 4,
                            Price = 89000m,
                            ProductName = "Ức gà tươi đông lạnh 1kg",
                            StockQuantity = 60
                        },
                        new
                        {
                            ProductId = 8,
                            Barcode = "8938501234568",
                            CategoryId = 4,
                            Price = 42000m,
                            ProductName = "Cơm gạo lứt đóng hộp ăn liền 250g",
                            StockQuantity = 45
                        },
                        new
                        {
                            ProductId = 9,
                            Barcode = "8938501234569",
                            CategoryId = 5,
                            Price = 145000m,
                            ProductName = "Dầu oliu nguyên chất Extra Virgin 500ml",
                            StockQuantity = 20
                        },
                        new
                        {
                            ProductId = 10,
                            Barcode = "8938501234570",
                            CategoryId = 5,
                            Price = 120000m,
                            ProductName = "Mật ong nguyên chất U Minh 500ml",
                            StockQuantity = 15
                        });
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Product", b =>
                {
                    b.HasOne("MiniSupermarket.API.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MiniSupermarket.API.Models.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
